name: Godot Automatic Build on Commit
on:
  push:
    tags:
    - 'v*'
jobs:
  webgl:
    name: Godot HTML5 Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: ETdoFresh/Actions/GodotBuild@latest
      with:
        GODOT_EXPORT_TARGET: HTML5
        GODOT_EXPORT_DIRECTORY: build/web
        GODOT_EXPORT_FILE: index.html
    - uses: ETdoFresh/Actions/UploadToGithubPages@latest
      with:
        DIRECTORY_TO_UPLOAD: build/web
        GITHUB_REPOSITORY: ETdoFresh/TileMapCreator
        GITHUB_USERNAME: ${{ secrets.USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_GEN_TOKEN }}

  windows:
    name: Godot Windows Desktop Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: ETdoFresh/Actions/GodotBuild@latest
      with:
        GODOT_EXPORT_TARGET: Windows Desktop
        GODOT_EXPORT_DIRECTORY: build/windows
        GODOT_EXPORT_FILE: tilemapcreator.exe
    - uses: actions/upload-artifact@v1
      with:
        name: windows
        path: build/windows
